BEGIN;

CREATE TABLE attempts (
  id SERIAL PRIMARY KEY,
  x FLOAT NOT NULL,
  y FLOAT NOT NULL,
  r FLOAT NOT NULL,
  result BOOLEAN NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  execution_time BIGINT NOT NULL
);

COMMIT;
